spring:
  application:
    name:
      api-cliente

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: root
    password: test
    driver-class-name: oracle.jdbc.OracleDriver

    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.Oracle12cDialect
      show-sql: true
