services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - C:\Users\pedro.cortivo\docker\volumes\rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/unfit-products-dev
      - RABBITMQ_DEFAULT_PERMISSION=./*.*.*
  oracle-server-db:
    container_name: oracle-free
    image: gvenzl/oracle-free
    ports:
      - "1521:1521"
    restart: always
    environment:
      - ORACLE_PASSWORD=senha
