spring:
  application:
    name:
      api-cliente

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/api_clientes
    username: system
    password: user
    driver-class-name: oracle.jdbc.OracleDriver

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "admin"
    virtual-host: "/unfit-products-dev"

